### ISSUE TITLE
Error: Cannot find module 'postcss'

### ISSUE THREAD

**Issue by joebudi** [dirkolbrich/hugo-theme-tailwindcss-starter#32]
I followed your instructions in the readme step by step, but I am getting the following error, when I run the following command:
`hugo server -s exampleSite --themesDir=../.. --disableFastRender`

Error: Error building site: POSTCSS: failed to transform "css/styles.css" (text/css): internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'postcss'
Require stack:
- /usr/local/lib/node_modules/postcss-cli/index.js
- /usr/local/lib/node_modules/postcss-cli/bin/postcss
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/postcss-cli/index.js:14:17)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/postcss-cli/index.js',
    '/usr/local/lib/node_modules/postcss-cli/bin/postcss'
  ]
}

I have installed the prerequisites.

**Comment by joebudi** [comment]
I managed to work around it by moving my config and content folders to root, and simply running `hugo serve`. I am not sure if this is a workaround or a flawed sense of progress, but I am getting no errors and the site is available.

**Comment by dirkolbrich** [comment]
Weird, as it works on my machine™.

Can you please run the following commands from your the root of the starter repo:
`npm list -depth=0`,  `npm list -depth=0 -g` and `hugo version`

You should see:
```bash
/Users/your-user-name/some-folder/hugo-theme-tailwindcss-starter
├── @fullhuman/postcss-purgecss@4.0.2
├── @tailwindcss/typography@0.4.0
├── autoprefixer@10.2.4
├── postcss-cli@8.3.1
├── postcss-import@14.0.0
├── postcss@8.2.6
└── tailwindcss@2.0.3
```

```bash
npm list -depth=0 -g
/usr/local/lib
├── autoprefixer@10.2.0
├── npm-check-updates@10.2.5
├── npm@7.6.3
├── postcss-cli@8.3.1
└── postcss@8.2.3
```

```bash
hugo version
hugo v0.82.0+extended darwin/amd64 BuildDate=unknown
```
