### ISSUE TITLE
I get "Error: Error building site: POSTCSS: failed to transform"

### ISSUE THREAD

**Issue by gurumark** [dirkolbrich/hugo-theme-tailwindcss-starter#42]
hugo server --disableFastRender
Start building sites … 
hugo v0.87.0 linux/amd64 BuildDate=2021-08-03T13:10:04Z
Error: Error building site: POSTCSS: failed to transform "css/styles.css" (text/css): TypeError: Object.fromEntries is not a function
    at Object.<anonymous> (/home/guruadm/codespace/sites/wpworkplace.com/node_modules/tailwindcss/lib/jit/corePlugins.js:242:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/guruadm/codespace/sites/wpworkplace.com/node_modules/tailwindcss/lib/jit/lib/setupContextUtils.js:36:43)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
Built in 593 ms

*** 
node -v
v16.6.1
***
npm -v
7.20.3
*****
cat package.json 
{
  "devDependencies": {
    "@fullhuman/postcss-purgecss": "^4.0.3",
    "@tailwindcss/typography": "^0.4.1",
    "postcss": "^8.3.6",
    "postcss-import": "^14.0.2",
    "tailwindcss": "^2.2.7",
    "tailwindcss-base-buttons": "github:thebakerdev/tailwindcss-base-buttons"
  },
  "dependencies": {
    "postcss-cli": "^8.3.1"
  },
  "name": "example.com",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "description": ""
}

Thank you

**Comment by gurumark** [comment]
The whole issue was related to installing Hugo from snap package. Once I installed it from the deb package, the issue got resolved.
Thank you for the project.
